version: '3.2'

networks:
  proxy_network:
    external: true
volumes:
  db-data:

services:
  database:
    image: mariadb
    container_name: database
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=database
    restart: always
    volumes:
      - /sessions
    networks:
      - default
      - proxy_network