version: '3.2'

networks:
  proxy_network:
    external: true
volumes:
  db-data:

services:
  express:
    build: .
    container_name: express
    restart: always
    volumes:
      - ../WEB(FE)/:/data/watchcon/app/web # debug bind
      #- ./:/data/watchcon/app # debug bind
    networks:
      - default
      - proxy_network
    # Release options
    # ports:
    #   - 80:8080

  database:
    image: mariadb
    container_name: database
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=database
    restart: always
    volumes:
      - /sessions
    networks:
      - default
      - proxy_network
    # Release options
    # ports:
    #   - 8080:80